### ISSUE TITLE
Undefined symbols error

### ISSUE THREAD

**Issue by djrain** [cengiz-pz/godot-ios-inapp-review-plugin#3]
Hi, I installed the plugin today from asset store, and when I try to export for iOS in Godot 4.3, I get this

Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftXPC", referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_godot_plugin in InappReviewPlugin.a(SwiftClass.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftXPC_$_godot_plugin)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Not sure if I missed a step or something?

**Comment by cengiz-pz** [comment]
Hi @djrain, I haven't seen the error that you encountered before. Would it be possible for you to attach a minimal project where this error is reproducible?

**Comment by cengiz-pz** [comment]
By the way, what version of Xcode are you using?  There are [reports](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1824#issuecomment-2060285783) that Xcode versions prior to 15.3 are producing this error.

**Comment by djrain** [comment]
Updating to Xcode 16 has solved it. Thanks!
