### ISSUE TITLE
Sir, can you share an ios in-app purchase plugin? We really need it!

### ISSUE THREAD

**Issue by dsyze** [cengiz-pz/godot-ios-inapp-review-plugin#4]

**Comment by cengiz-pz** [comment]
Hi @dsyze, there is a Godot-maintained plugin that may provide the functionality that you're looking for.  Check the following link:

https://github.com/godot-sdk-integrations/godot-ios-plugins/tree/master/plugins/inappstore

**Comment by dsyze** [comment]
> Hi @dsyze, there is a Godot-maintained plugin that may provide the functionality that you're looking for. Check the following link:
> 
> https://github.com/godot-sdk-integrations/godot-ios-plugins/tree/master/plugins/inappstore

Thanks.i will ryt.
